# Configurable options and examples:
#   https://github.com/bbatsov/rubocop/blob/master/config/default.yml

# How to use .rubocop_todo.yml
#   https://github.com/bbatsov/rubocop#automatically-generated-configuration

inherit_from: .rubocop_todo.yml

Style/CollectionMethods:
  Description: Preferred collection methods.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#map-find-select-reduce-size
  Enabled: true
  PreferredMethods:
    collect: map
    collect!: map!
    detect: find
    find:
    find_all: select
    inject: reduce
